# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Shayan Shekarforoush
title: Research Scientist
email: shekshaa.75@gmail.com
# website: shekshaa.github.io

# Social links
# twitter_username: facespics
researchgate_username: Shayan_Shekarforoush
github_username:  shekshaa
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
googlescholar_username: ABanXIYAAAAJ
linkedin_username: shayan-shekarforoush-597508136
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/pf.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is **Shayan Shekarforoush** and I am currently studying his bachelor’s degree in Computer Engineering at [Sharif University of Technology](http://www.sharif.ir).
  My research interests include Deep Learning in particular, and Machine Learning in general, with applications in Computer Vision and Graph Learning. 
  My motivation to pursue research in these areas stems from my strong desire to better understand these methods in a principled manner by investigating 
  both their mathematical underpinning and their practical implications in real life and in our society. 
  Although the techniques proposed in these fields have demonstrated considerable performance gain in recent years, 
  major challenges in terms of understanding their underlying mathematical foundations remain unresolved. 
  My ultimate goal in my doctoral studies is to channel such better theoretical and functional understanding of 
  these new technologies towards better practical solutions for real life problems.
  
# Projects Section
projects_title: Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Science and Technology, some of my other hobbies are:
   - Rock Music
   - Ultimate Frisbee
   - Basketball
   - Playing Tennis

# Footer
footer_show_references: true

# Build settings
remote_theme: shekshaa/shekshaa.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
