# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Shayan Shekarforoush
title: Research Scientist
email: shekshaa.75@gmail.com
# website: shekshaa.github.io

# Social links
# twitter_username: facespics
github_username:  shekshaa
researchgate_username: Shayan_Shekarforoush
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: shayan-shekarforoush-597508136
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/pf.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently in my fourth year of bachelor’s degree in Computer Engineering at Sharif University of Technology, the top technical university of Iran. 
  
  My field of interest includes Deep Learning and Machine Learning, with applications to Medical Imaging and Computer Vision.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in ML/DL some of my other interests and hobbies are:
   - Ultimate Frisbee
   - Basketball

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
